export const TipsURL = import.meta.env.VITE_SERVER_URL_TIPS || "http://localhost:5001/tips"
export const ResourceURL = import.meta.env.VITE_SERVER_URL_RESOURCES || "http://localhost:5001/resources"
export const loginURL = import.meta.env.VITE_SERVER_URL_USER_LOGIN || "http://localhost:5001/users/login"
export const infoURL = import.meta.env.VITE_SERVER_URL_USER_INFO || "http://localhost:5001/users/getInfo"
export const registerURL = import.meta.VITE_SERVER_URL_USER_REGISTER || "http://localhost:5001/users/register"
export const footPrintURL = import.meta.VITE_SERVER_URL_FOOTPRINT || "http://localhost:5001/carbonFootprint"
